-- E-COMMERCE SCHEMA
CREATE TABLE customers (
                           customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           first_name  VARCHAR2(50) NOT NULL,
                           last_name   VARCHAR2(50) NOT NULL,
                           email       VARCHAR2(100) UNIQUE NOT NULL,
                           created_at  DATE DEFAULT SYSDATE
);

CREATE TABLE products (
                          product_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name        VARCHAR2(100) NOT NULL,
                          description VARCHAR2(500),
                          price       NUMBER(10,2) NOT NULL CHECK (price >= 0),
                          stock_qty   NUMBER DEFAULT 0 CHECK (stock_qty >= 0)
);

CREATE TABLE orders (
                        order_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        customer_id  NUMBER NOT NULL,
                        order_date   DATE DEFAULT SYSDATE,
                        total_amount NUMBER(12,2) NOT NULL CHECK (total_amount >= 0),
                        CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id)
                            REFERENCES customers(customer_id) ON DELETE CASCADE
);

CREATE TABLE order_items (
                             order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id      NUMBER NOT NULL,
                             product_id    NUMBER NOT NULL,
                             quantity      NUMBER NOT NULL CHECK (quantity > 0),
                             unit_price    NUMBER(10,2) NOT NULL CHECK (unit_price >= 0),
                             CONSTRAINT fk_order_items_order FOREIGN KEY (order_id)
                                 REFERENCES orders(order_id) ON DELETE CASCADE,
                             CONSTRAINT fk_order_items_product FOREIGN KEY (product_id)
                                 REFERENCES products(product_id)
);

-- EMPLOYEE TIME TRACKING
CREATE TABLE employees (
                           employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           first_name  VARCHAR2(50) NOT NULL,
                           last_name   VARCHAR2(50) NOT NULL,
                           hire_date   DATE DEFAULT SYSDATE
);

CREATE TABLE work_logs (
                           log_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           employee_id NUMBER NOT NULL,
                           work_date   DATE NOT NULL,
                           hours_worked NUMBER(5,2) NOT NULL CHECK (hours_worked >= 0),
                           CONSTRAINT fk_work_logs_employee FOREIGN KEY (employee_id)
                               REFERENCES employees(employee_id) ON DELETE CASCADE
);
