-- BASIC E-COMMERCE (NO CONSTRAINTS)

CREATE TABLE customers (
                           customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                           name        VARCHAR2(100) NOT NULL,
                           email       VARCHAR2(100),
                           created_at  DATE DEFAULT SYSDATE
);

CREATE TABLE products (
                          product_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
                          name        VARCHAR2(100) NOT NULL,
                          price       NUMBER(10,2),
                          stock_qty   NUMBER
);

CREATE TABLE orders (
                        order_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
                        customer_id   NUMBER,
                        order_date    DATE DEFAULT SYSDATE,
                        total_amount  NUMBER(12,2),
                        status        VARCHAR2(20),
                        completed_at  DATE,
                        updated_at    DATE DEFAULT SYSDATE
);

CREATE INDEX ix_orders_status      ON orders(status);
CREATE INDEX ix_orders_order_date  ON orders(order_date);

CREATE TABLE order_items (
                             order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                             order_id      NUMBER,
                             product_id    NUMBER,
                             quantity      NUMBER,
                             unit_price    NUMBER(10,2)
);

-- BASIC TIME TRACKING (NO CONSTRAINTS)

CREATE TABLE employees (
                           employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                           name        VARCHAR2(100),
                           hire_date   DATE DEFAULT SYSDATE
);

CREATE TABLE work_logs (
                           log_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
                           employee_id  NUMBER,
                           work_date    DATE,
                           hours_worked NUMBER(5,2)
);
